apiVersion: v1
kind: Service
metadata:
  name: book-service
  labels:
    app: book-service 
spec:
  type: NodePort
  selector:
    app: book-service
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
      nodePort: 30080
