apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: book-app-servicemonitor
  namespace: monitoring 
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: book-service 
  namespaceSelector:
    any: true 
  endpoints:
  - port: http-metrics 
    path: /metrics      
    interval: 15s       
